### ISSUE TITLE
[Docker Compose] V2 GA

### ISSUE THREAD

**Issue by stephanierifai** [docker/roadmap#256]
**Tell us about your request**
Move [Docker Compose v2](https://github.com/docker/roadmap/issues/15) from release candidate to generally available and make it the default version for all OS.

**Which service(s) is this request for?**
Dev-tools

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
The goal of compose v2 was to align on Go for most of our development. In order to focus our time towards new features and enhancements, we need to make v2 the default and phase out v1. Turning this option on by default in Docker Desktop users, will allows users can seamlessly move to Docker Compose V2 without the need to upgrade any of their scripts. 

**Are you currently working around the issue?**
N/A 

**Additional context**
Proposed Timeline:
🔏 As of September 28th, 2021 new features and bug fixes will only be considered in the V2 codebase. Users will be defaulted into Docker Compose V2. Users can still opt out through the UI and the cli. Docker Compose V1  will only be maintained regarding security issues.
🔐 On December 28th, 2021 Docker Compose V1 will be marked as deprecated. 
🔒 By March 28th, 2022 no new contribution will be accepted to the V1 branch, even for security fixes.

**Comment by masatana** [comment]
Hi,

Is this still "Almost There"?

**Comment by stephanierifai** [comment]
Hi! Yes, still in almost there. We're going to time the GA with the next release of the CLI, which right now we don't have a definitive timeline for. We wanted to make sure there was an easy install path for Linux users before we called this GA. A bit more details here: https://docs.docker.com/compose/cli-command/#transitioning-to-ga-for-compose-v2 ! Let me know if that helps :)

**Comment by tstibbs** [comment]
Any news on this? Looks like there's been two cli releases since the comment above (20.10.13 and 20.10.14) so did the transition to GA happen or is there something else holding it up?

If it's still in progress, it would be useful to see the tickets that relate to that so it's clear what's outstanding. As it currently stands, it's very unclear just how GA-ready v2 is (so difficult to know whether to switch in an enterprise environment).

**Comment by stephanierifai** [comment]
Hi! We're very close to the announcement on GA (about a month or so), there are no technical barriers from using it in an enterprise environment. We had yet to call it generally available since it prior to the 20.10.13 release it was not easily available Linux, now that we have done that we are working on transitioning our docs and guides to make v2 the default!

**Comment by nemchik** [comment]
The packages that have been made available have been very helpful! I can't wait to see a full inclusion into cli, and/or installation via https://github.com/docker/docker-install

**Comment by stephanierifai** [comment]
Hi all! Yesterday marked GA, check out the announcement [here](https://www.docker.com/blog/announcing-compose-v2-general-availability/)!

**Comment by nemchik** [comment]
> Hi all! Yesterday marked GA, check out the announcement [here](https://www.docker.com/blog/announcing-compose-v2-general-availability/)!

This is great news!

Is there a specific version of compose v2 that is considered GA?

I ask because the latest version [released on GitHub](https://github.com/docker/compose/releases) as of writing is 2.4.1 while the latest version available from the [docker-ce repository](https://download.docker.com/) is currently 2.3.3 (which has some issues that were fixed in 2.4.x). Per a [previous comment](https://github.com/docker/compose/issues/9195#issuecomment-1098777498) it seems like there is work being done to get the repository updated more regularly.

**Comment by ndeloof** [comment]
@nemchik G.A doesn't apply to a specific version of compose v2, we use this terminology to qualify software being considered stable (while, obviously, some bugs still can exist) _and_ available on all supported platform, which is the case as docker-ce-repository now offers compose v2 for Linux as system packages. Those are not updated yet with latest release but will be soon. We are also working on making our packaging pipeline more flexible so we can keep version in sync without such delays.

**Comment by nemchik** [comment]
> @nemchik G.A doesn't apply to a specific version of compose v2, we use this terminology to qualify software being considered stable (while, obviously, some bugs still can exist) _and_ available on all supported platform, which is the case as docker-ce-repository now offers compose v2 for Linux as system packages. Those are not updated yet with latest release but will be soon. We are also working on making our packaging pipeline more flexible so we can keep version in sync without such delays.

Thanks for the follow up! I appreciate the explanation and all the work you've done!

**Comment by johnthagen** [comment]
@stephanierifai Now that GA is announced, will new Compose V2 Docker images be released?

- https://github.com/docker/compose/issues/8871

This is the final blocker our company has to fully switching over to Compose V2.

**Comment by stephanierifai** [comment]
hi @johnthagen I think you saw, but we shipped it and now closed it! Thanks for the feedback :D
